version : '3'
services :
  app:
    build: .
    depends_on:
      - db_websocket
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_websocket:5432/courses
      - SPRING_DATASOURCE_USERNAME=demo
      - SPRING_DATASOURCE_PASSWORD=demo
    networks:
      - spring-docker-websocket
  db_websocket:
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=courses
    networks:
      - spring-docker-websocket
    ports:
      - "15432:5432"
    volumes:
      - ./db_websocket:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - spring-docker-websocket

volumes:
  db_data:
    driver: local
networks:
  spring-docker-websocket:
    driver: bridge