--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: courses; Type: SCHEMA; Schema: -; Owner: demo
--

CREATE SCHEMA courses;


ALTER SCHEMA courses OWNER TO demo;

--
-- Name: messages; Type: SCHEMA; Schema: -; Owner: demo
--

CREATE SCHEMA messages;


ALTER SCHEMA messages OWNER TO demo;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: demo
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO demo;

SET default_tablespace = '';

SET default_table_access_method = heap;


--
-- Name: databasechangelog; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE courses.databasechangelog OWNER TO demo;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE courses.databasechangeloglock OWNER TO demo;

--
-- Name: roles; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.roles (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    status character varying(25) DEFAULT 'ACTIVE'::character varying NOT NULL
);


ALTER TABLE courses.roles OWNER TO demo;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: courses; Owner: demo
--

ALTER TABLE courses.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME courses.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.user_roles (
    user_id bigint,
    role_id bigint
);


ALTER TABLE courses.user_roles OWNER TO demo;

--
-- Name: users; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.users (
    id bigint NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    status character varying(25) DEFAULT 'ACTIVE'::character varying NOT NULL
);


ALTER TABLE courses.users OWNER TO demo;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: courses; Owner: demo
--

ALTER TABLE courses.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME courses.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: messages; Owner: demo
--

CREATE TABLE messages.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE messages.databasechangelog OWNER TO demo;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: messages; Owner: demo
--

CREATE TABLE messages.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE messages.databasechangeloglock OWNER TO demo;

--
-- Name: messages; Type: TABLE; Schema: messages; Owner: demo
--

CREATE TABLE messages.messages (
    id bigint NOT NULL,
    created timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated timestamp(6) without time zone DEFAULT now() NOT NULL,
    text character varying(255) NOT NULL,
    sender bigint,
    receiver bigint,
    status character varying(255),
    CONSTRAINT messages_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'NOT_ACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);


ALTER TABLE messages.messages OWNER TO demo;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: messages; Owner: demo
--

ALTER TABLE messages.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME messages.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: messages; Owner: demo
--

CREATE TABLE messages.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated timestamp(6) without time zone DEFAULT now() NOT NULL,
    status character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL
);


ALTER TABLE messages.roles OWNER TO demo;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: messages; Owner: demo
--

ALTER TABLE messages.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME messages.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: messages; Owner: demo
--

CREATE TABLE messages.user_roles (
    user_id bigint,
    role_id bigint
);


ALTER TABLE messages.user_roles OWNER TO demo;

--
-- Name: users; Type: TABLE; Schema: messages; Owner: demo
--

CREATE TABLE messages.users (
    id bigint NOT NULL,
    username character varying(255),
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL,
    created timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated timestamp(6) without time zone DEFAULT now() NOT NULL,
    status character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL
);


ALTER TABLE messages.users OWNER TO demo;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: messages; Owner: demo
--

ALTER TABLE messages.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME messages.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
create_course_table	SobolevOE	db/changelog/changelog-master.xml	2023-07-06 16:40:58.751667	1	EXECUTED	8:a49cb4acf18468de6ffc47009d2c920c	createTable tableName=course		\N	4.20.0	\N	\N	8650858607
1.0.0	SobolevOE	db/changelog/changelog-1.0.xml	2023-07-09 18:07:36.392748	2	EXECUTED	8:323ac074ef1d24beafcc25a59fda7e53	createTable tableName=users		\N	4.20.0	\N	\N	8915255464
1.0.1	SobolevOE	db/changelog/changelog-1.0.xml	2023-07-09 18:07:36.549635	3	EXECUTED	8:11097fc07407ce7d5d6acc771037dd57	createTable tableName=roles		\N	4.20.0	\N	\N	8915255464
1.0.2	SobolevOE	db/changelog/changelog-1.0.xml	2023-07-09 18:07:36.614111	4	EXECUTED	8:efe450563d1252f1c819a159bf11122f	createTable tableName=user_roles		\N	4.20.0	\N	\N	8915255464
1.0.3	SobolevOE	db/changelog/changelog-1.0.xml	2023-07-09 18:07:36.683028	5	EXECUTED	8:85920099fbdefe1c4483c64fdd18d31b	addForeignKeyConstraint baseTableName=user_roles, constraintName=fk_user_roles_user, referencedTableName=users		\N	4.20.0	\N	\N	8915255464
1.0.4	SobolevOE	db/changelog/changelog-1.0.xml	2023-07-09 18:07:37.981681	6	EXECUTED	8:be48f2c8fe179c55dcc8fe24404a1163	addForeignKeyConstraint baseTableName=user_roles, constraintName=fk_user_roles_roles, referencedTableName=roles		\N	4.20.0	\N	\N	8915255464
1.0.5	SobolevOE	db/changelog/changelog-1.0.xml	2023-07-09 18:07:38.048211	7	EXECUTED	8:5101d2209c508a5c240ea48a30223474	insert tableName=roles; insert tableName=roles		\N	4.20.0	\N	\N	8915255464
alter-table-course	joopinho	db/changelog/changelog-1.0.xml	2023-07-10 18:31:54.773172	8	EXECUTED	8:67fa0b7982b384fb25389922fea7c884	addColumn tableName=users		\N	4.20.0	\N	\N	9003114647
1.0.6	SobolevOE	db/changelog/changelog-1.0.xml	2023-07-11 11:16:03.584709	9	EXECUTED	8:f850b848becbe3a5c56fd6e32ce39c03	insert tableName=roles		\N	4.20.0	\N	\N	9063363440
1.0.7	SobolevOE	db/changelog/changelog-1.0.xml	2023-07-11 15:33:54.072194	10	EXECUTED	8:aa09c63d5e327765fc80f115f59090ea	dropColumn tableName=users		\N	4.20.0	\N	\N	9078833822
1.0.8	SobolevOE	db/changelog/changelog-1.1.xml	2023-07-12 22:25:50.512121	11	EXECUTED	8:62bb964134a4d73de70d6bbc4b5fc47c	addColumn tableName=course; addColumn tableName=course; addColumn tableName=course		\N	4.20.0	\N	\N	9189950424
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.roles (id, name, created, updated, status) FROM stdin;
1	ROLE_USER	2023-07-09 18:07:38.006607	2023-07-09 18:07:38.006607	ACTIVE
2	ROLE_ADMIN	2023-07-09 18:07:38.006607	2023-07-09 18:07:38.006607	ACTIVE
3	ROLE_MODERATOR	2023-07-11 11:16:03.448061	2023-07-11 11:16:03.448061	ACTIVE
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.user_roles (user_id, role_id) FROM stdin;
1	1
1	2
8	1
10	1
11	1
11	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.users (id, username, email, first_name, last_name, password, created, updated, status) FROM stdin;
1	test	test@test.test	test	test	$2a$04$oWv/60MC7yAY6mE.45SB/e6QqxqpL55JmFW33Ntn10zd3UViYdbM2	2023-07-10 13:12:05	2023-07-10 13:12:09	ACTIVE
10	test222@test222.test222	test222@test222.test222	test222	test222	$2a$10$K82RDIjiPVQEgVcEp2cSNOhkHSHEviyrkjc7GCl5FvavkprMiCj96	2023-07-11 16:15:01.944	2023-07-11 16:15:01.944	NOT_ACTIVE
8	1test111@test111.test111	test111@test111.test111	test111	test111	$2a$10$9vGeW8xowVVLFkeb68Gs6OmX38fL3pVgv5C5FIzqysSUZiyV.p8bK	2023-07-11 15:44:59.417	2023-07-11 15:44:59.417	ACTIVE
11	test333@test333.test333	test333@test333.test333	test333	test333	$2a$10$q.fbMY1M.iGRAWo2vLVUCO/Vk9R15djrztVLpR.CL57.MWL/Nn3xK	2023-07-24 13:44:57.459	2023-07-24 13:44:57.459	ACTIVE
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: messages; Owner: demo
--

COPY messages.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
1.0.0	SobolevOE	db/changelog/changes/changelog-1.0.xml	2023-07-22 20:22:18.848394	1	EXECUTED	8:186dc3a20645a98aa234b0c34f1193a4	createTable tableName=users		\N	4.20.0	\N	\N	0046537360
1.0.1	SobolevOE	db/changelog/changes/changelog-1.0.xml	2023-07-22 20:22:19.072599	2	EXECUTED	8:73c5f886d8cc289141b665d9f3d0b393	createTable tableName=roles		\N	4.20.0	\N	\N	0046537360
1.0.2	SobolevOE	db/changelog/changes/changelog-1.0.xml	2023-07-22 20:22:19.1309	3	EXECUTED	8:e2657507382694075376c05d451dd4d4	createTable tableName=user_roles		\N	4.20.0	\N	\N	0046537360
1.0.3	SobolevOE	db/changelog/changes/changelog-1.0.xml	2023-07-22 20:22:19.191078	4	EXECUTED	8:b18dedb9d0671bbd5e4d68a4bda25488	addForeignKeyConstraint baseTableName=user_roles, constraintName=fk_user_roles_user, referencedTableName=users		\N	4.20.0	\N	\N	0046537360
1.0.4	SobolevOE	db/changelog/changes/changelog-1.0.xml	2023-07-22 20:22:19.248393	5	EXECUTED	8:738e0a250e62d402dfa7ddcc52af9fa7	addForeignKeyConstraint baseTableName=user_roles, constraintName=fk_user_roles_roles, referencedTableName=roles		\N	4.20.0	\N	\N	0046537360
1.0.5	SobolevOE	db/changelog/changes/changelog-1.0.xml	2023-07-22 20:22:19.306055	6	EXECUTED	8:94539e2ff50f539b4d3a969aaf5ac6bb	insert tableName=roles; insert tableName=roles; insert tableName=roles		\N	4.20.0	\N	\N	0046537360
1.0.6	SobolevOE	db/changelog/changes/changelog-1.1.xml	2023-07-22 20:22:22.926449	7	EXECUTED	8:929c07a9fbe912532d3b372e42049820	createTable tableName=messages		\N	4.20.0	\N	\N	0046537360
1.0.7	SobolevOE	db/changelog/changes/changelog-1.1.xml	2023-07-22 20:22:23.817491	8	EXECUTED	8:9f732c3c0e60751b1fc6b158fe1accc1	addForeignKeyConstraint baseTableName=messages, constraintName=fk_messages_sender_user, referencedTableName=users		\N	4.20.0	\N	\N	0046537360
1.0.8	SobolevOE	db/changelog/changes/changelog-1.1.xml	2023-07-22 20:22:25.058438	9	EXECUTED	8:0050b7b7245b2ee31bf2d1a18fe44d55	addForeignKeyConstraint baseTableName=messages, constraintName=fk_messages_receiver_user, referencedTableName=users		\N	4.20.0	\N	\N	0046537360
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: messages; Owner: demo
--

COPY messages.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: messages; Owner: demo
--

COPY messages.messages (id, created, updated, text, sender, receiver, status) FROM stdin;
1	2023-07-22 20:38:40.8	2023-07-22 20:38:40.8	sdfsdf	1	\N	ACTIVE
2	2023-07-22 20:39:04.804	2023-07-22 20:39:04.804	sdfdsf	2	\N	ACTIVE
3	2023-07-22 20:39:09.599	2023-07-22 20:39:09.599	test222@test222.test222	1	2	ACTIVE
4	2023-07-22 20:39:15.38	2023-07-22 20:39:15.38	test111@test111.test111	2	1	ACTIVE
5	2023-07-22 20:46:56.378	2023-07-22 20:46:56.378		1	\N	ACTIVE
6	2023-07-22 20:47:02.815	2023-07-22 20:47:02.815	test111@test111.test111	1	\N	ACTIVE
7	2023-07-22 20:47:12.436	2023-07-22 20:47:12.436	test111@test111.test111	1	1	ACTIVE
8	2023-07-22 20:49:28.864	2023-07-22 20:49:28.864	test222@test222.test222	1	2	ACTIVE
9	2023-07-22 20:49:32.981	2023-07-22 20:49:32.981	test111@test111.test111	2	1	ACTIVE
10	2023-07-22 20:52:43.2	2023-07-22 20:52:43.2	dsfsdf	2	\N	ACTIVE
11	2023-07-22 20:52:47.127	2023-07-22 20:52:47.127	test222@test222.test222	1	2	ACTIVE
12	2023-07-22 20:52:51.669	2023-07-22 20:52:51.669	test111@test111.test111	2	1	ACTIVE
13	2023-07-22 20:53:01.903	2023-07-22 20:53:01.903	hello1!	2	1	ACTIVE
14	2023-07-22 20:53:09.068	2023-07-22 20:53:09.068	hello2!	1	2	ACTIVE
15	2023-07-22 21:06:02.645	2023-07-22 21:06:02.645	dsfdsf	1	\N	ACTIVE
16	2023-07-22 21:06:48.702	2023-07-22 21:06:48.702	dfsfdsfsdf	2	\N	ACTIVE
17	2023-07-22 21:07:00.63	2023-07-22 21:07:00.63	привет!	1	2	ACTIVE
18	2023-07-22 21:07:13.385	2023-07-22 21:07:13.385	хай	2	1	ACTIVE
19	2023-07-22 21:22:36.219	2023-07-22 21:22:36.219	fdsfsdfsdf	2	\N	ACTIVE
20	2023-07-22 21:22:42.811	2023-07-22 21:22:42.811	test222@test222.test222	1	2	ACTIVE
21	2023-07-22 21:22:46.748	2023-07-22 21:22:46.748	test111@test111.test111	2	1	ACTIVE
22	2023-07-22 22:36:32.618	2023-07-22 22:36:32.618	sdfdsf	1	\N	ACTIVE
23	2023-07-22 22:36:37.623	2023-07-22 22:36:37.623	test111@test111.test111	1	1	ACTIVE
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: messages; Owner: demo
--

COPY messages.roles (id, name, created, updated, status) FROM stdin;
1	ROLE_USER	2023-07-22 20:22:19.281268	2023-07-22 20:22:19.281268	ACTIVE
2	ROLE_ADMIN	2023-07-22 20:22:19.281268	2023-07-22 20:22:19.281268	ACTIVE
3	ROLE_MODERATOR	2023-07-22 20:22:19.281268	2023-07-22 20:22:19.281268	ACTIVE
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: messages; Owner: demo
--

COPY messages.user_roles (user_id, role_id) FROM stdin;
1	1
2	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: messages; Owner: demo
--

COPY messages.users (id, username, email, first_name, last_name, password, created, updated, status) FROM stdin;
1	\N	test111@test111.test111	test111	\N	$2a$10$tzCvx6VPoiSf.pqPs0XuWe79BXey4l2v9a/ws1h6D3JpjRZb44kJq	2023-07-22 20:22:48.758	2023-07-22 20:22:48.758	ACTIVE
2	test222@test222.test222	test222@test222.test222	test222	\N	$2a$10$IUoVS200uqtmppWQI9OO6OnVOD3D9OeoxfcuXdladcaVwaqRgVTMS	2023-07-22 20:23:53.548	2023-07-22 20:23:53.548	ACTIVE
\.


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: courses; Owner: demo
--

SELECT pg_catalog.setval('courses.roles_id_seq', 3, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: courses; Owner: demo
--

SELECT pg_catalog.setval('courses.users_id_seq', 11, true);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: messages; Owner: demo
--

SELECT pg_catalog.setval('messages.messages_id_seq', 23, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: messages; Owner: demo
--

SELECT pg_catalog.setval('messages.roles_id_seq', 3, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: messages; Owner: demo
--

SELECT pg_catalog.setval('messages.users_id_seq', 2, true);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_roles fk_user_roles_roles; Type: FK CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.user_roles
    ADD CONSTRAINT fk_user_roles_roles FOREIGN KEY (role_id) REFERENCES courses.roles(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: user_roles fk_user_roles_user; Type: FK CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES courses.users(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: messages fk_messages_receiver_user; Type: FK CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.messages
    ADD CONSTRAINT fk_messages_receiver_user FOREIGN KEY (receiver) REFERENCES messages.users(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: messages fk_messages_sender_user; Type: FK CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.messages
    ADD CONSTRAINT fk_messages_sender_user FOREIGN KEY (sender) REFERENCES messages.users(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: user_roles fk_user_roles_roles; Type: FK CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.user_roles
    ADD CONSTRAINT fk_user_roles_roles FOREIGN KEY (role_id) REFERENCES messages.roles(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: user_roles fk_user_roles_user; Type: FK CONSTRAINT; Schema: messages; Owner: demo
--

ALTER TABLE ONLY messages.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES messages.users(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

